# Generated by Django 4.1.4 on 2022-12-27 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year_begin', models.SmallIntegerField()),
                ('year_end', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.make')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.generation')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.model')),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('start_production', models.SmallIntegerField()),
                ('end_production', models.SmallIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.model')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=70)),
                ('unit', models.CharField(max_length=70)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specification')),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trim')),
            ],
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.equipment')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.option')),
            ],
        ),
        migrations.AddField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='core.model'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='trim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trim'),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('mileage', models.SmallIntegerField()),
                ('vin', models.CharField(max_length=70)),
                ('availability', models.BooleanField(default=False)),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.generation')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.model')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.serie')),
                ('trim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trim')),
            ],
        ),
    ]
